-- ============================================================
-- Verification for migration 064 (the join flow can record fields)
-- ============================================================
-- Paste into the Supabase SQL editor and run. Scratch template, invitation and
-- participant; everything it makes is deleted.
--
-- This reproduces an anonymous participant joining by invitation link: the
-- `anon` role, with the invitation code presented the way PostgREST presents
-- it, in request.headers. Run against a database without 064 the first check
-- fails, which is the bug that was reported from production.

BEGIN;

CREATE TEMP TABLE _result(seq int, check_name text, outcome text, detail text) ON COMMIT DROP;
CREATE TEMP TABLE _fx(k text PRIMARY KEY, v text) ON COMMIT DROP;
GRANT ALL ON _result TO anon;
GRANT ALL ON _fx TO anon;

DO $fx$
DECLARE v_a uuid; v_tpl uuid; v_field uuid; v_code text; v_other text; v_p uuid; v_p2 uuid;
BEGIN
  SELECT id INTO v_a FROM auth.users ORDER BY created_at LIMIT 1;

  INSERT INTO templates (name, user_id) VALUES ('ZZ join fields', v_a)
    RETURNING id INTO v_tpl;
  INSERT INTO template_participant_fields (template_id, label, field_type, sort_order)
    VALUES (v_tpl, 'ZZ course', 'text', 0) RETURNING id INTO v_field;

  v_code := 'zzjoin' || substr(md5(random()::text), 1, 8);
  INSERT INTO session_invitations
      (template_id, user_id, code, is_active, evaluator_name, selected_task_ids)
    VALUES (v_tpl, v_a, v_code, true, 'ZZ evaluator', '{}'::uuid[]);

  -- A participant created the way the join flow creates one: owned by the
  -- evaluator who issued the invitation, with its id generated by the client.
  v_p := gen_random_uuid();
  INSERT INTO participants (id, name, user_id) VALUES (v_p, 'ZZ joiner', v_a);

  -- Someone else's participant, to prove the code does not open everything.
  v_p2 := gen_random_uuid();
  INSERT INTO participants (id, name, user_id) VALUES (v_p2, 'ZZ outsider', v_a);

  INSERT INTO _fx VALUES ('tpl', v_tpl::text), ('field', v_field::text),
                         ('code', v_code), ('p', v_p::text), ('p2', v_p2::text);
END $fx$;

-- ── as an anonymous participant holding the invitation code ──
SET LOCAL ROLE anon;

DO $anon$
DECLARE v_field uuid; v_code text; v_p uuid; v_p2 uuid; n int;
BEGIN
  SELECT v::uuid INTO v_field FROM _fx WHERE k = 'field';
  SELECT v INTO v_code FROM _fx WHERE k = 'code';
  SELECT v::uuid INTO v_p FROM _fx WHERE k = 'p';
  SELECT v::uuid INTO v_p2 FROM _fx WHERE k = 'p2';

  PERFORM set_config(
    'request.headers',
    json_build_object('x-invite-code', v_code)::text,
    true);

  -- ── 1. the reported failure ───────────────────────────────
  BEGIN
    INSERT INTO participant_field_values (participant_id, field_id, value)
      VALUES (v_p, v_field, 'ZZ Informatics');
    INSERT INTO _result VALUES (1, 'a joining participant can record a field answer', 'PASS', '');
  EXCEPTION WHEN OTHERS THEN
    INSERT INTO _result VALUES (1, 'a joining participant can record a field answer', 'FAIL', SQLERRM);
  END;

  -- ── 2. and it is actually there ───────────────────────────
  -- Read back as the owner below; anon cannot see participants at all, which
  -- is the whole reason the policy needed a definer function.
  INSERT INTO _result VALUES (2, 'anon still cannot read the participants table',
    CASE WHEN (SELECT count(*) FROM participants WHERE id = v_p) = 0
         THEN 'PASS' ELSE 'FAIL' END,
    'visible=' || (SELECT count(*) FROM participants WHERE id = v_p));

  -- ── 3. the code does not open every participant ───────────
  -- Both belong to the same evaluator here, so this one is allowed and says
  -- so: the rule is ownership by the inviter, not identity of the participant.
  BEGIN
    INSERT INTO participant_field_values (participant_id, field_id, value)
      VALUES (v_p2, v_field, 'ZZ other');
    INSERT INTO _result VALUES (3, 'the rule is the inviter owns the participant', 'PASS',
      'allowed, both belong to the inviter');
  EXCEPTION WHEN OTHERS THEN
    INSERT INTO _result VALUES (3, 'the rule is the inviter owns the participant', 'FAIL', SQLERRM);
  END;

  -- ── 4. without a code, nothing ────────────────────────────
  PERFORM set_config('request.headers', json_build_object('x-invite-code', '')::text, true);
  BEGIN
    INSERT INTO participant_field_values (participant_id, field_id, value)
      VALUES (v_p, v_field, 'ZZ no code');
    INSERT INTO _result VALUES (4, 'no invitation code, no write', 'FAIL', 'insert succeeded');
  EXCEPTION WHEN OTHERS THEN
    INSERT INTO _result VALUES (4, 'no invitation code, no write', 'PASS', SQLERRM);
  END;

  -- ── 5. a wrong code is no code ────────────────────────────
  PERFORM set_config('request.headers',
    json_build_object('x-invite-code', 'zz-not-a-real-code')::text, true);
  BEGIN
    INSERT INTO participant_field_values (participant_id, field_id, value)
      VALUES (v_p, v_field, 'ZZ wrong code');
    INSERT INTO _result VALUES (5, 'a code that matches no invitation is refused', 'FAIL', 'insert succeeded');
  EXCEPTION WHEN OTHERS THEN
    INSERT INTO _result VALUES (5, 'a code that matches no invitation is refused', 'PASS', SQLERRM);
  END;
END $anon$;

RESET ROLE;

DO $after$
DECLARE v_p uuid; n int;
BEGIN
  SELECT v::uuid INTO v_p FROM _fx WHERE k = 'p';
  SELECT count(*) INTO n FROM participant_field_values WHERE participant_id = v_p;
  INSERT INTO _result VALUES (6, 'the answer the participant gave is stored',
    CASE WHEN n = 1 THEN 'PASS' ELSE 'FAIL' END, 'rows=' || n);
END $after$;

DO $clean$
DECLARE v_tpl uuid; v_p uuid; v_p2 uuid;
BEGIN
  SELECT v::uuid INTO v_tpl FROM _fx WHERE k = 'tpl';
  SELECT v::uuid INTO v_p FROM _fx WHERE k = 'p';
  SELECT v::uuid INTO v_p2 FROM _fx WHERE k = 'p2';
  DELETE FROM session_invitations WHERE template_id = v_tpl;
  DELETE FROM test_sessions WHERE template_id = v_tpl;
  DELETE FROM templates WHERE id = v_tpl;
  DELETE FROM participants WHERE id IN (v_p, v_p2);
END $clean$;

SELECT seq, check_name, outcome, left(detail, 90) AS detail FROM _result ORDER BY seq;

COMMIT;
