/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as ParticipantsIndexRouteImport } from './routes/participants/index'
import { Route as MyTemplatesIndexRouteImport } from './routes/my-templates/index'
import { Route as MySessionsIndexRouteImport } from './routes/my-sessions/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as TemplatesNewRouteImport } from './routes/templates/new'
import { Route as SessionsNewRouteImport } from './routes/sessions/new'
import { Route as ParticipantsNewRouteImport } from './routes/participants/new'
import { Route as ParticipantsParticipantIdRouteImport } from './routes/participants/$participantId'
import { Route as JoinCodeRouteImport } from './routes/join/$code'
import { Route as TemplatesTemplateIdIndexRouteImport } from './routes/templates/$templateId/index'
import { Route as SessionsSessionIdIndexRouteImport } from './routes/sessions/$sessionId/index'
import { Route as MySessionsSessionIdIndexRouteImport } from './routes/my-sessions/$sessionId/index'
import { Route as SessionsSessionIdLiveRouteImport } from './routes/sessions/$sessionId/live'
import { Route as SessionsSessionIdEditRouteImport } from './routes/sessions/$sessionId/edit'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantsIndexRoute = ParticipantsIndexRouteImport.update({
  id: '/participants/',
  path: '/participants/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTemplatesIndexRoute = MyTemplatesIndexRouteImport.update({
  id: '/my-templates/',
  path: '/my-templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const MySessionsIndexRoute = MySessionsIndexRouteImport.update({
  id: '/my-sessions/',
  path: '/my-sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesNewRoute = TemplatesNewRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsNewRoute = SessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantsNewRoute = ParticipantsNewRouteImport.update({
  id: '/participants/new',
  path: '/participants/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantsParticipantIdRoute =
  ParticipantsParticipantIdRouteImport.update({
    id: '/participants/$participantId',
    path: '/participants/$participantId',
    getParentRoute: () => rootRouteImport,
  } as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdIndexRoute =
  TemplatesTemplateIdIndexRouteImport.update({
    id: '/templates/$templateId/',
    path: '/templates/$templateId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionsSessionIdIndexRoute = SessionsSessionIdIndexRouteImport.update({
  id: '/sessions/$sessionId/',
  path: '/sessions/$sessionId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MySessionsSessionIdIndexRoute =
  MySessionsSessionIdIndexRouteImport.update({
    id: '/my-sessions/$sessionId/',
    path: '/my-sessions/$sessionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionsSessionIdLiveRoute = SessionsSessionIdLiveRouteImport.update({
  id: '/sessions/$sessionId/live',
  path: '/sessions/$sessionId/live',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdEditRoute = SessionsSessionIdEditRouteImport.update({
  id: '/sessions/$sessionId/edit',
  path: '/sessions/$sessionId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/join/$code': typeof JoinCodeRoute
  '/participants/$participantId': typeof ParticipantsParticipantIdRoute
  '/participants/new': typeof ParticipantsNewRoute
  '/sessions/new': typeof SessionsNewRoute
  '/templates/new': typeof TemplatesNewRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/my-sessions/': typeof MySessionsIndexRoute
  '/my-templates/': typeof MyTemplatesIndexRoute
  '/participants/': typeof ParticipantsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/sessions/$sessionId/edit': typeof SessionsSessionIdEditRoute
  '/sessions/$sessionId/live': typeof SessionsSessionIdLiveRoute
  '/my-sessions/$sessionId/': typeof MySessionsSessionIdIndexRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
  '/templates/$templateId/': typeof TemplatesTemplateIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/join/$code': typeof JoinCodeRoute
  '/participants/$participantId': typeof ParticipantsParticipantIdRoute
  '/participants/new': typeof ParticipantsNewRoute
  '/sessions/new': typeof SessionsNewRoute
  '/templates/new': typeof TemplatesNewRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/my-sessions': typeof MySessionsIndexRoute
  '/my-templates': typeof MyTemplatesIndexRoute
  '/participants': typeof ParticipantsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/sessions/$sessionId/edit': typeof SessionsSessionIdEditRoute
  '/sessions/$sessionId/live': typeof SessionsSessionIdLiveRoute
  '/my-sessions/$sessionId': typeof MySessionsSessionIdIndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdIndexRoute
  '/templates/$templateId': typeof TemplatesTemplateIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/join/$code': typeof JoinCodeRoute
  '/participants/$participantId': typeof ParticipantsParticipantIdRoute
  '/participants/new': typeof ParticipantsNewRoute
  '/sessions/new': typeof SessionsNewRoute
  '/templates/new': typeof TemplatesNewRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/my-sessions/': typeof MySessionsIndexRoute
  '/my-templates/': typeof MyTemplatesIndexRoute
  '/participants/': typeof ParticipantsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/sessions/$sessionId/edit': typeof SessionsSessionIdEditRoute
  '/sessions/$sessionId/live': typeof SessionsSessionIdLiveRoute
  '/my-sessions/$sessionId/': typeof MySessionsSessionIdIndexRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
  '/templates/$templateId/': typeof TemplatesTemplateIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/complete-profile'
    | '/login'
    | '/profile'
    | '/join/$code'
    | '/participants/$participantId'
    | '/participants/new'
    | '/sessions/new'
    | '/templates/new'
    | '/analytics/'
    | '/my-sessions/'
    | '/my-templates/'
    | '/participants/'
    | '/sessions/'
    | '/templates/'
    | '/sessions/$sessionId/edit'
    | '/sessions/$sessionId/live'
    | '/my-sessions/$sessionId/'
    | '/sessions/$sessionId/'
    | '/templates/$templateId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/complete-profile'
    | '/login'
    | '/profile'
    | '/join/$code'
    | '/participants/$participantId'
    | '/participants/new'
    | '/sessions/new'
    | '/templates/new'
    | '/analytics'
    | '/my-sessions'
    | '/my-templates'
    | '/participants'
    | '/sessions'
    | '/templates'
    | '/sessions/$sessionId/edit'
    | '/sessions/$sessionId/live'
    | '/my-sessions/$sessionId'
    | '/sessions/$sessionId'
    | '/templates/$templateId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/complete-profile'
    | '/login'
    | '/profile'
    | '/join/$code'
    | '/participants/$participantId'
    | '/participants/new'
    | '/sessions/new'
    | '/templates/new'
    | '/analytics/'
    | '/my-sessions/'
    | '/my-templates/'
    | '/participants/'
    | '/sessions/'
    | '/templates/'
    | '/sessions/$sessionId/edit'
    | '/sessions/$sessionId/live'
    | '/my-sessions/$sessionId/'
    | '/sessions/$sessionId/'
    | '/templates/$templateId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  JoinCodeRoute: typeof JoinCodeRoute
  ParticipantsParticipantIdRoute: typeof ParticipantsParticipantIdRoute
  ParticipantsNewRoute: typeof ParticipantsNewRoute
  SessionsNewRoute: typeof SessionsNewRoute
  TemplatesNewRoute: typeof TemplatesNewRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  MySessionsIndexRoute: typeof MySessionsIndexRoute
  MyTemplatesIndexRoute: typeof MyTemplatesIndexRoute
  ParticipantsIndexRoute: typeof ParticipantsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  SessionsSessionIdEditRoute: typeof SessionsSessionIdEditRoute
  SessionsSessionIdLiveRoute: typeof SessionsSessionIdLiveRoute
  MySessionsSessionIdIndexRoute: typeof MySessionsSessionIdIndexRoute
  SessionsSessionIdIndexRoute: typeof SessionsSessionIdIndexRoute
  TemplatesTemplateIdIndexRoute: typeof TemplatesTemplateIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participants/': {
      id: '/participants/'
      path: '/participants'
      fullPath: '/participants/'
      preLoaderRoute: typeof ParticipantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-templates/': {
      id: '/my-templates/'
      path: '/my-templates'
      fullPath: '/my-templates/'
      preLoaderRoute: typeof MyTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-sessions/': {
      id: '/my-sessions/'
      path: '/my-sessions'
      fullPath: '/my-sessions/'
      preLoaderRoute: typeof MySessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/new': {
      id: '/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof TemplatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/new': {
      id: '/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof SessionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participants/new': {
      id: '/participants/new'
      path: '/participants/new'
      fullPath: '/participants/new'
      preLoaderRoute: typeof ParticipantsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participants/$participantId': {
      id: '/participants/$participantId'
      path: '/participants/$participantId'
      fullPath: '/participants/$participantId'
      preLoaderRoute: typeof ParticipantsParticipantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId/': {
      id: '/templates/$templateId/'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId/'
      preLoaderRoute: typeof TemplatesTemplateIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/': {
      id: '/sessions/$sessionId/'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof SessionsSessionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-sessions/$sessionId/': {
      id: '/my-sessions/$sessionId/'
      path: '/my-sessions/$sessionId'
      fullPath: '/my-sessions/$sessionId/'
      preLoaderRoute: typeof MySessionsSessionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/live': {
      id: '/sessions/$sessionId/live'
      path: '/sessions/$sessionId/live'
      fullPath: '/sessions/$sessionId/live'
      preLoaderRoute: typeof SessionsSessionIdLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/edit': {
      id: '/sessions/$sessionId/edit'
      path: '/sessions/$sessionId/edit'
      fullPath: '/sessions/$sessionId/edit'
      preLoaderRoute: typeof SessionsSessionIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CompleteProfileRoute: CompleteProfileRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  JoinCodeRoute: JoinCodeRoute,
  ParticipantsParticipantIdRoute: ParticipantsParticipantIdRoute,
  ParticipantsNewRoute: ParticipantsNewRoute,
  SessionsNewRoute: SessionsNewRoute,
  TemplatesNewRoute: TemplatesNewRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  MySessionsIndexRoute: MySessionsIndexRoute,
  MyTemplatesIndexRoute: MyTemplatesIndexRoute,
  ParticipantsIndexRoute: ParticipantsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  SessionsSessionIdEditRoute: SessionsSessionIdEditRoute,
  SessionsSessionIdLiveRoute: SessionsSessionIdLiveRoute,
  MySessionsSessionIdIndexRoute: MySessionsSessionIdIndexRoute,
  SessionsSessionIdIndexRoute: SessionsSessionIdIndexRoute,
  TemplatesTemplateIdIndexRoute: TemplatesTemplateIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
